-- Lucas Reid Lab6 COMP325
1.SELECT P_CODE,P_DESCRIPT  FROM LAB5_PRODUCT WHERE P_QOH >(SELECT avg(P_QOH)from LAB5_PRODUCT);

2.SELECT P_CODE, P_PRICE, ROUND(P_PRICE - (select avg(P_PRICE) from LAB5_PRODUCT),2)
FROM LAB5_PRODUCT;

3.select P_CATEGORY, sum(P_PRICE) from LAB5_PRODUCT group by P_CATEGORY
having  sum(P_PRICE)> (select AVG(P_PRICE) FROM LAB5_PRODUCT 
WHERE P_CATEGORY = 1);

4.SELECT AVG(sumPrice) FROM
(SELECT sum(P_PRICE) AS sumPrice from LAB5_PRODUCT GROUP BY P_CATEGORY); 

5.SELECT * From LAB5_PRODUCT where V_CODE IN
(SELECT V_CODE FROM LAB5_VENDOR WHERE V_NAME LIKE 'B%');

6.SELECT * FROM LAB5_PRODUCT WHERE P_QOH > ALL(SELECT P_QOH FROM LAB5_PRODUCT WHERE 
P_CATEGORY = 1);

7.select * from LAB5_PRODUCT outer where P_QOH >(SELECT AVG(P_QOH)FROM LAB5_PRODUCT inner where 
inner.P_CATEGORY = outer.P_CATEGORY);

8.SELECT CUS_CODE, CUS_LNAME from LAB5_CUSTOMER outer WHERE NOT EXISTS (SELECT CUS_CODE,INV_DATE 
FROM LAB5_INVOICE inner WHERE INV_DATE<SYSDATE AND inner.CUS_CODE = outer.CUS_CODE);

9.SELECT V_CODE, V_NAME from LAB5_VENDOR outer WHERE EXISTS
(SELECT V_CODE FROM LAB5_PRODUCT inner WHERE P_QOH<(2*P_MIN) AND inner.V_CODE = outer.V_CODE); 

10.SELECT INV_NUMBER FROM LAB5_INVOICE WHERE INV_NUMBER IN
(SELECT INV_NUMBER FROM LAB5_LINE WHERE P_CODE IN
(SELECT P_CODE from LAB5_PRODUCT WHERE V_CODE IN(
SELECT V_CODE FROM LAB5_VENDOR WHERE V_STATE = 'TN')));
