-- Lucas Reid COMP325-01 Lab3

1. CREATE TABLE Lab3_Employees (EMP_ID INTEGER PRIMARY KEY, EMP_TITLE VARCHAR(30) NOT NULL, EMP_LNAME VARCHAR(30) NOT NULL, EMP_FNAME VARCHAR(30) NOT NULL, EMP_HIREDATE DATE NOT NULL, EMP_SALARY NUMERIC(8,2) DEFAULT 0.0, EMP_BONUS DOUBLE NOT NULL);

2.INSERT INTO Lab3_Employees (EMP_ID, EMP_TITLE, EMP_LNAME, EMP_FNAME, EMP_HIREDATE, EMP_SALARY,EMP_BONUS) VALUES (1, 'Senior Programmer', 'Martin', 'Joseph', '2000-10-10', '68000', .06);

INSERT INTO Lab3_Employees (EMP_ID,EMP_TITLE,EMP_LNAME, EMP_FNAME, EMP_HIREDATE, EMP_SALARY,EMP_BONUS) VALUES (2, 'Senior Programmer', 'Stimer', 'Jay', '2010-01-09', '68000', .04);

INSERT INTO Lab3_Employees (EMP_ID,EMP_TITLE, EMP_LNAME, EMP_FNAME, EMP_HIREDATE, EMP_SALARY,EMP_BONUS ) VALUES (3, 'Programmer', 'Andrews', 'Robyn', '2006-12-08', '42030', .02);

INSERT INTO Lab3_Employees (EMP_ID, EMP_TITLE,EMP_LNAME, EMP_FNAME, EMP_HIREDATE, EMP_SALARY,EMP_BONUS ) VALUES (4, 'Project Manager', 'Reid', 'Lucas', '2000-04-01', '98000', .1);

INSERT INTO Lab3_Employees (EMP_ID, EMP_TITLE,EMP_LNAME, EMP_FNAME, EMP_HIREDATE, EMP_SALARY,EMP_BONUS ) VALUES (5, 'programmer', 'Harris', 'Tom', '2004-04-04', '42030', .02);

INSERT INTO Lab3_Employees (EMP_ID, EMP_TITLE,EMP_LNAME, EMP_FNAME, EMP_HIREDATE, EMP_SALARY,EMP_BONUS ) VALUES (6, 'Programmer', 'Williams', 'Roy', '2011-10-12', '42030', .02);

INSERT INTO Lab3_Employees (EMP_ID, EMP_TITLE,EMP_LNAME, EMP_FNAME, EMP_HIREDATE, EMP_SALARY,EMP_BONUS ) VALUES (7, 'Human Resourses', 'Arnald', 'Marry', '2003-08-11', '63000', .03);

INSERT INTO Lab3_Employees (EMP_ID, EMP_TITLE,EMP_LNAME, EMP_FNAME, EMP_HIREDATE, EMP_SALARY,EMP_BONUS ) VALUES (8, 'District Manager', 'Hiles', 'Daphne', '2000-04-02', '100220', .09);

3.ALTER TABLE Lab3_Employees ADD EMP_GENDER CHAR(1) NOT NULL;

4.ALTER TABLE Lab3_Employees ADD CONSTRAINT  Lab3_check_gender CHECK (EMP_GENDER IN ('M', 'F','N'));

5.ALTER TABLE Lab3_Employees ADD EMP_STATUS CHAR(1) NOT NULL;

ALTER TABLE Lab3_Employees ADD CONSTRAINT Lab3_check_status CHECK(EMP_STATUS IN('F','P','R'));

6.
UPDATE Lab3_Employees SET EMP_GENDER = 'M' WHERE EMP_ID = 1;
UPDATE Lab3_Employees SET EMP_GENDER = 'M' WHERE EMP_ID = 2;
UPDATE Lab3_Employees SET EMP_GENDER = 'M' WHERE EMP_ID = 4;
UPDATE Lab3_Employees SET EMP_GENDER = 'M' WHERE EMP_ID = 5;
UPDATE Lab3_Employees SET EMP_GENDER = 'M' WHERE EMP_ID = 6;
UPDATE Lab3_Employees SET EMP_GENDER = 'F' WHERE EMP_ID = 3;
UPDATE Lab3_Employees SET EMP_GENDER = 'F' WHERE EMP_ID = 7;
UPDATE Lab3_Employees SET EMP_GENDER = 'F' WHERE EMP_ID = 8;

UPDATE Lab3_Employees SET EMP_STATUS = 'F' WHERE EMP_ID = 1;
UPDATE Lab3_Employees SET EMP_STATUS = 'F' WHERE EMP_ID = 2;
UPDATE Lab3_Employees SET EMP_STATUS = 'P' WHERE EMP_ID = 3;
UPDATE Lab3_Employees SET EMP_STATUS = 'F' WHERE EMP_ID = 4;
UPDATE Lab3_Employees SET EMP_STATUS = 'R' WHERE EMP_ID = 5;
UPDATE Lab3_Employees SET EMP_STATUS = 'P' WHERE EMP_ID = 6;
UPDATE Lab3_Employees SET EMP_STATUS = 'F' WHERE EMP_ID = 7;
UPDATE Lab3_Employees SET EMP_STATUS = 'F' WHERE EMP_ID = 8;

7.ALTER TABLE Lab3_Employees ADD CONSTRAINT Lab3_check_status CHECK(EMP_SALARY >= 0.0);

8.CREATE TABLE Lab3_Departments (DEPT_ID INTEGER PRIMARY KEY, DEPT_NAME VARCHAR(30) NOT NULL);

INSERT INTO Lab3_Departments (DEPT_ID, DEPT_NAME) VALUES (10, 'Software Engineering');
INSERT INTO Lab3_Departments (DEPT_ID, DEPT_NAME) VALUES (11, 'Systems');
INSERT INTO Lab3_Departments (DEPT_ID, DEPT_NAME) VALUES (12, 'Networking');
INSERT INTO Lab3_Departments (DEPT_ID, DEPT_NAME) VALUES (13, 'Managerial');
INSERT INTO Lab3_Departments (DEPT_ID, DEPT_NAME) VALUES (0, 'Unassigned');

9.ALTER TABLE Lab3_Employees ADD DEPT_ID INTEGER NOT NULL;
ALTER TABLE Lab3_Employees ADD CONSTRAINT DEPT_FK FOREIGN KEY (DEPT_ID) REFERENCES Lab3_Departments(DEPT_ID);


10.
UPDATE Lab3_Employees SET DEPT_ID = '10' WHERE EMP_ID = 1;
UPDATE Lab3_Employees SET DEPT_ID = '10' WHERE EMP_ID = 2;
UPDATE Lab3_Employees SET DEPT_ID = '0' WHERE EMP_ID = 3;
UPDATE Lab3_Employees SET DEPT_ID = '11' WHERE EMP_ID = 4;
UPDATE Lab3_Employees SET DEPT_ID = '0' WHERE EMP_ID = 5;
UPDATE Lab3_Employees SET DEPT_ID = '10' WHERE EMP_ID = 6;
UPDATE Lab3_Employees SET DEPT_ID = '13' WHERE EMP_ID = 7;
UPDATE Lab3_Employees SET DEPT_ID = '13' WHERE EMP_ID = 8;

11,SELECT EMP_ID, EMP_LNAME FROM Lab3_Employees WHERE DEPT_ID = 0;

12,SELECT * FROM Lab3_Employees WHERE Lab3_Employees.DEPT_ID =  (SELECT DEPT_ID FROM Lab3_Departments WHERE DEPT_NAME = 'Software Engineering');

13,SELECT COUNT(*) FROM Lab3_Employees NATURAL JOIN Lab3_Departments WHERE Lab3_Departments.DEPT_NAME='Software Engineering';

14,SELECT * FROM Lab3_Employees NATURAL JOIN Lab3_Departments WHERE Lab3_Departments.DEPT_NAME='Software Engineering';

15.SELECT EMP_ID, EMP_LNAME, EMP_FNAME, EMP_SALARY FROM Lab3_Employees WHERE EMP_SALARY >(SELECT AVG(EMP_SALARY) FROM Lab3_Employees);

16.SELECT EMP_ID, EMP_LNAME,EMP_SALARY FROM Lab3_Employees WHERE Lab3_Employees.EMP_SALARY BETWEEN (SELECT AVG(EMP_SALARY)*.5 FROM Lab3_Employees) AND (SELECT AVG(EMP_SALARY)*1.5 FROM Lab3_Employees);

17.SELECT EMP_ID, EMP_LNAME,EMP_SALARY FROM Lab3_Employees WHERE EMP_SALARY IN (SELECT EMP_SALARY FROM Lab3_Employees WHERE EMP_SALARY BETWEEN (EMP_SALARY * EMP_BONUS)AND(EMP_SALARY*EMP_BONUS));

18.SELECT EMP_SALARY, EMP_BONUS, EMP_TITLE FROM (SELECT * FROM Lab3_Employees JOIN Lab3_Department WHERE EMP_TITLE = 'Programmer');

19. 

20. SELECT EMP_TITLE, AVG(EMP_SALARY), STD(EMP_SALARY) FROM Lab3_Employees GROUP BY EMP_TITLE;


















